# Circle CI configuration file

version 2.1

jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01

    steps:
      - run:
          name: Build
          command: mvn clean install

workflows:
  configserver:
    jobs: build